extends: "airbnb"
parser: "babel-eslint"
rules:
  comma-dangle: 0
  class-methods-use-this: 0
  jsx-quotes: 0
  max-len: [1, 100, {
    ignoreUrls: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true,
  }]
  no-shadow: 0
  semi: [2, "never"]

  react/jsx-curly-spacing: [2, "always"]
  react/jsx-filename-extension: [1, { extensions: [".js", ".jsx"] }]
  react/forbid-prop-types: 0
