blogTitle = "cannoneyed"
header = "cannoneyed.github.io"
authorName = "Andy Coenen"
shortName = "cannoneyed"
linkPrefix = ""
domain = "https://cannoneyed.github.io"
email = "andrew.coenen@gmail.com"
description = "Andy Coenen - Software developer and artist living and working in San Francisco."
